version: '3'
services:
  db:
    image: postgres:9.4
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hellofc_development
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/tmp/var/lib/postgresql/data
